---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/vpc-output_vars
    - name: Import vprofile setup Variable
      include_vars: vars/vprostacksetup
    - name: Create vprofile ec2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed